/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        roboto: ["Roboto", "sans-serif"],
        inter: ["Inter", "sans-serif"], 
        interSemibold: ["Inter", "sans-serif"], 
        interBold: ["Inter", "sans-serif"],
        jakarta: ["'Plus Jakarta Sans'", "sans-serif"],
        neuething: ["NeuethingSans", "sans-serif"],
        berlinsans: ["BerlinSans", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        outfit: ["Outfit", "sans-serif"],
      },
      spacing: {
        128: "32rem",
        144: "36rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      screens: {
        xs: "375px",
        sm: "480px",
        md: "768px",
        lg: "976px",
        xl: "1440px",
        lxl: "1652px",
        max666: { max: "665px" },
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        black: "#000000",
        lightBlack: "#333333",
        border: "hsl(0, 0%, 89.8%)",
        lightblack: {
          100: "#1E1E1E",
          200: "#151515",
          300: "#404742",
        },
        gray: {
          25: "#F8F6F4",
          30: "#E4E6E4",
          75: "#BCBCBC",
          80: "#EFF0EF",
          90: "#b6b6b6",
          100: "#F8FAFA",
          200: "#E9ECEF",
          300: "#DEE2E6",
          310: "#DDDDDD",
          320: "#D8D8D8",
          400: "#CED4DA",
          500: "#ADB5BD",
          510: "#A2A1A1",
          600: "#6C757D",
          700: "#495057",
          710: "#5E5E5E",
          800: "#343A40",
          900: "#212529",
          1000: "#121212",
        },
        blue: {
          25: "#F0F9FF",
          50: "#EFF6FF",
          75: "#DBEAFE",
          80: "#0567D4",
          100: "#BFDBFE",
          200: "#93C5FD",
          300: "#4F37FD", 
          400: "#2563EB",
          500: "#1D4ED8",
          600: "#1E40AF",
          700: "#1E3A8A",
          800: "#1E3A8A",
          900: "#1E3A8A",
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("tailwind-scrollbar"),
  ],
};
